---

- name: HAProxy | Install
  package: name={{ item }} state=present
  tags: 
    - patroni
    - haproxy
  with_items:
    - haproxy
  when: install is defined

- name: HAProxy | put config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg backup=yes
  tags: 
    - patroni
    - haproxy
  register: haproxy_configuration
  
- name: HAProxy | restart and enable
  service: name=haproxy state=restarted enabled=yes
  tags: 
    - patroni
    - haproxy
  when: haproxy_configuration.changed

