---

- name: Keepalived | Install
  pacman: name={{ item }} state=present
  tags: 
    - patroni
    - keepalived
  with_items:
    - keepalived
  when: install is defined

- name: Keepalived | put alert script
  template: src=alert.sh.j2 dest=/usr/local/sbin/alert.sh backup=no mode=755
  tags: 
    - patroni
    - keepalived
  when: install is defined

- name: Keepalived | put config
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf backup=yes
  tags: 
    - patroni
    - keepalived
  register: keepalived_configuration
  
- name: Keepalived | restart and enable
  service: name=keepalived state=restarted enabled=yes
  tags: 
    - patroni
    - keepalived
  when: keepalived_configuration.changed


