patroni_cluster_data_dir: "{{ postgresql_conf_directory }}"
patroni_cluster_name: patroni-cluster
patroni_consul_host: 127.0.0.1:8500
patroni_consul_url: http://127.0.0.1:8500

postgresql_conf_directory: /var/lib/postgres_cluster/data
postgresql_unix_socket_directories: /run/postgresql

# Parameters must hold the same values on the master and the replicas
postgresql_max_connections: 100
postgresql_max_locks_per_transaction: 64
postgresql_max_worker_processes: 8
postgresql_max_prepared_transactions: 0
postgresql_wal_level: logical
postgresql_wal_log_hints: on
postgresql_track_commit_timestamp: off

# Parameter values for bootstrap
postgresql_archive_mode: off
postgresql_archive_command: ""
postgresql_archive_timeout: 0
postgresql_max_wal_senders: 10
postgresql_wal_keep_segments:  0
postgresql_max_replication_slots: 10

# pg_hba.conf for bootstrap
postgresql_default_auth_method: "trust"
postgresql_pg_hba_default:
  - { type: local, database: all,         user: all, address: "",             method: "{{ postgresql_default_auth_method }}", comment: '"local" is for Unix domain socket connections only' }
  - { type: host,  database: all,         user: all, address: "127.0.0.1/32", method: "{{ postgresql_default_auth_method }}", comment: "IPv4 local connections:" }
  - { type: host,  database: all,         user: all, address: "::1/128",      method: "{{ postgresql_default_auth_method }}", comment: "IPv6 local connections:" }
  - { type: local, database: replication, user: all, address: "",             method: "peer",                                 comment: "Allow replication connections from localhost, by a user with the replication privilege" }
  - { type: host,  database: replication, user: all, address: "127.0.0.1/32", method: "md5" }
  - { type: host,  database: replication, user: all, address: "::1/128",      method: "md5" }

postgresql_pg_hba_custom:
  - { type: host, database: all, user: all, address: "100.100.0.0/16", method: "md5"}

# Keepalived
keepalived_vrrp_instance_interface: eth0

# HAproxy
postgresql_port: 5432
postgresql_port_rewritten: 5433
postgresql_port_readonly: 5431

pgbouncer_listen_port: 6432
pgbouncer_listen_port_rewritten: 6433
pgbouncer_listen_port_readonly: 6431